source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem "rest_in_place", :path => ".."

gem 'sqlite3'
gem 'json'

gem 'sass-rails',   '~> 3.1.5'
gem 'coffee-rails', '~> 3.1.1'
gem 'uglifier', '>= 1.0.3'

gem 'jquery-rails'
