source 'http://rubygems.org'

gem 'rails', '~>3.2'
gem "rest_in_place", :path => ".."

gem 'sqlite3'
gem 'json'

gem 'sass-rails',   '~> 3.1'
gem 'coffee-rails', '~> 3.1'
gem 'uglifier', '>= 1.0.3'

gem 'jquery-rails'
